### ISSUE TITLE
minimap2 -I option

### ISSUE THREAD

**Issue by diego-rt** [Maggi-Chen/Inspector#10]
Hi,

Because of my genome size I need to specific the minimap2 -I parameter to a larger number. Is it possible to simply provide Inspector with the bam file rather than with a fastq file? It also would make things way easier when working on a cluster where I can distribute the mapping jobs.

Thanks!

**Comment by Maggi-Chen** [comment]
Hi,

Thank you for the suggestions. I think you can use your own sorted BAM with the '--skip_read_alignment' in Inspector. Basically you will need to:
1. Align reads to assembly with minimap2 -I and sort BAM file
2. Create a softlink to the sorted BAM file in the output directory of Inspector (make sure the BAM file is named as 'read_to_contig.bam')
3. Run Inspector with --skip_read_alignment 

This should work for your case. Pleas let me know if you have met ant problems with this.

Thanks.
