### ISSUE TITLE
Consistency in formatting of summary_statistics

### ISSUE THREAD

**Issue by lcoombe** [Maggi-Chen/Inspector#11]
Hello,

I'm trying out Inspector, and noticed that there are some inconsistencies with the formatting of the file `summary_statistics`. For example, most header/value pairs are tab-separated, but not in all cases: 

For example in this script writing to the `summary_statistics` file:
https://github.com/Maggi-Chen/Inspector/blob/master/denovo_static.py
lines 230-233 write a tab, but lines 451-452 do not.

Having consistent formatting of `header\tvalue` would be helpful for parsing the output file on the command-line. 

Thanks for developing this tool!
Lauren

**Comment by Maggi-Chen** [comment]
Hello Lauren,

Thank you for pointing this out! I think these few lines were missed last time I edited it. I have fixed this in the latest version. Thank you for using Inspector!

Thanks,
Maggi

**Comment by lcoombe** [comment]
Great - thanks so much!
