### ISSUE TITLE
Structural Error increased after the inspector polishing

### ISSUE THREAD

**Issue by HaoChen-PGG** [Maggi-Chen/Inspector#12]
Hi inspector Team,
    I used the inspector to perform assembly correction of two haplotype-resolved HiFi assemblies of a human individual. I can see the assembly QV is better, but one of assemblies shows more structural errors after correction. In addition, I also found the local assembly would fail in inspector correction. Is it possible for me to address these issues? Thanks!

commands:
inspector.py -c asm1.fa -r ccsreads.1.fastq ccsreads.2.fastq -o asm1_out/ --datatype hifi
inspector.py -c asm2.fa -r ccsreads.1.fastq ccsreads.2.fastq -o asm2_out/ --datatype hifi

inspector-correct.py -i asm1_out/ --datatype pacbio-hifi -o asm1_corrected/
inspector-correct.py -i asm2_out/ --datatype pacbio-hifi -o asm2_corrected/

**asm2 before correction:**
Structural error        49
Expansion       29
Collapse        20
Haplotype switch        0
Inversion       0

Small-scale assembly error /per Mbp     14.790265745042309
Total small-scale assembly error        44683
Base substitution       26180
Small-scale expansion   10097
Small-scale collapse    8406

QV      46.40314095738277

**asm2 after correction:**
Structural error        58
Expansion       32
Collapse        26
Haplotype switch        0
Inversion       0

Small-scale assembly error /per Mbp     1.3369275599703823
Total small-scale assembly error        4039
Base substitution       3227
Small-scale expansion   349
Small-scale collapse    463

QV      50.03862621625856

**Comment by AndreaGuarracino** [comment]
@HaoChen-PGG, how did you solve this?
