### ISSUE TITLE
 minimap2: command not found

### ISSUE THREAD

**Issue by mergi-2674** [Maggi-Chen/Inspector#13]
Hi Maggi,
I was running Inspector on the assembled genome on a cluster node with 128 Gb of ram and 48 threads, I installed all the dependencies and run Inspector. However after running for a while it crushed a couple of times and gave me the same error.
 
"sh: minimap2: command not found
samtools sort: failed to read header from "-"
mv: cannot stat ‘/STORAGE/DATA/xxx/xxxx/flye_assembly/read_to_contig_1.bam’: No such file or directory
[E::hts_open_format] Failed to open file "//STORAGE/DATA/xxx/xxxx/Ins_flye_assembly/read_to_contig.bam" : No such file or directory
samtools index: failed to open "/STORAGE/DATA/xxx/xxxx/Ins_flye_assembly/read_to_contig.bam": No such file or directory
cat: /STORAGE/DATA/xxx/xxxx/Ins_flye_assembly/debreak_workspace/read_to_contig_*debreak.temp: No such file or directory
Traceback (most recent call last):
  File "/home/apps/user_apps/xxx/xxx_apps/Inspector/inspector.py", line 131, in <module>
    cov=denovo_static.mapping_info_ctg(denovo_args.outpath,chromosomes_large,chromosomes_small,totalcontiglen,totalcontiglen_large)
  File "/home/apps/user_apps/piwczyn/mergi_apps/Inspector/denovo_static.py", line 123, in mapping_info_ctg
    unmapped=int(pysam.AlignmentFile(outpath+'read_to_contig.bam','rb').unmapped)
  File "pysam/calignmentfile.pyx", line 318, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4730)
  File "pysam/calignmentfile.pyx", line 534, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7261)
IOError: file `//STORAGE/DATA/xxx/xxxx/Ins_flye_assembly/read_to_contig.bam` not found "

How should it get fixed?

Thanks ,

**Comment by Maggi-Chen** [comment]
Hello Mergi,

I think the major problem is that “minimap2” was not found, so the read alignment was not done, which caused all the following errors. 

Could you double check if you have minimap2  executable in your PATH? For example, if you run “minimap2 -h” in your terminal, could you see the manual of minimap2? If you could not print the minimap2 manual, you will need to install it and make sure to add the path to minimap2 to your $PATH. 


Best,
Maggi
