### ISSUE TITLE
Inspector error

### ISSUE THREAD

**Issue by mergi-2674** [Maggi-Chen/Inspector#16]
Hi Maggi,

I have been using Inspector to check the assembled genome through Flye. However, continuously it gives me the same error even if I changed some default parameters. Here is the error, How it should be fixed? thanks

/home/xxxxx/Inspector/inspector.py -c genome.fasta -r genome.fastq.gz -d nanopore -t 20
.
.
.
.
.
.
Collect info from scaffold_96561_np12_RagTag_polished
Collect info from scaffold_97192_np12_RagTag_polished
Collect info from scaffold_97806_np12_RagTag_polished
Collect info from scaffold_97933_np12_RagTag_polished
Collect info from scaffold_98921_np12_RagTag_polished
sh: 1: cat: Argument list too long
sh: 1: cat: Argument list too long
sh: 1: cat: Argument list too long
Traceback (most recent call last):
  File "/home/xxxxxxx/Inspector/inspector.py", line 131, in <module>
    cov=denovo_static.mapping_info_ctg(denovo_args.outpath,chromosomes_large,chromosomes_small,totalcontiglen,totalcontiglen_large)
  File "/home/xxxxxx/Inspector/denovo_static.py", line 138, in mapping_info_ctg
    splrate=round(10000*float(splitread)/mapped)/100.0
ZeroDivisionError: float division by zero

Best,
Mergi

**Comment by Maggi-Chen** [comment]
Hello Mergi,

According to the error massage, it seems none of the reads are mapped to the contigs. Could you check the output directory and see if 'valid_contig.fa' contains contigs? If so, could you check if read_to_contig.bam contains read alignments with flag of 0 or 16?

Thanks,
Maggi

**Comment by RickyW94** [comment]
Hi, I'm getting the exact same issue. 'valid_contig.fa' contains contigs and 'read_to_contig.bam' contains read alignments with flags of 0, 16, 2048, 2064, etc. I'm curious to know if this was resolved and how.

**Comment by fka21** [comment]
Hello, I'd also like to confirm this issue. As @Maggi-Chen asked I have checked that the valid_contigs.fa does in fact have entries and as @RickyW94 mentioned there are flags of different values present in the read_to_contig.bam (0, 16, 2048, 2046, 272, etc.). Has there been any progress on this error?

**Comment by RickyW94** [comment]
@fka21 I gave up as there has been no response.

**Comment by fka21** [comment]
I'd like to point out that `sh: 1: cat: Argument list too long` is before the zero division error message. From my understanding bash cannot handle so many input arguments (in the original poster's assembly I believe 98k contigs, each with a separate file). I also had 38k contigs. Maybe some intermediate file is made through `cat` command, but it is empty and hence the zero division.

To this I'd like to add:
```
$ wc -l inspector_report/djap-default/read_to_contig.debreak.temp
216677 inspector_report/djap-default/read_to_contig.debreak.temp

$ wc -l inspector_report/djap-default/debreak_workspace/read_to_contig_lcl_ptg0* | awk '{total += $1} END {print total}'
433354
```

Thoughts?
