### ISSUE TITLE
Can Inspector be used in homological polyploidy?

### ISSUE THREAD

**Issue by zhangyixing3** [Maggi-Chen/Inspector#17]
hi , Thank you for developing such a good software。 Your article write that we have developed Inspector  to comprehensively evaluate assembly quality and identify assembly errors **in haploid and diploid genomes**. Can I use Inspector to find structural assembly errors in homological polyploidy genome ?

**Comment by Maggi-Chen** [comment]
Hello Zhangyixing,

Yes, it can be applied on homological polyploid genomes. As far as there are always fewer than 3 (so <=2) alleles, Inspector can identify assembly errors accurately.

Thanks,
Maggi
