### ISSUE TITLE
Inspector seems doesn't fix the small-scale errors

### ISSUE THREAD

**Issue by hq66** [Maggi-Chen/Inspector#19]
Hi~ 
I used the command "inspector.py -c ctg.fa -r ccs1.fq ccs2.fq -o inspector_out/ --datatype hifi" to evaluate the ctg-level draft assembly. But I found the output "valid_contig.fa" was exactly the same as the input "ctg.fa". I careflly compared the size of contigs and the base sequence in "small_scale_error.bed", and I'm sure the "valid_contig.fa" makes no difference. The "summary_statistics" did output errors, but I wonder why they were not fixed in "valid_contig.fa".

**Comment by Maggi-Chen** [comment]
Hello,

The script 'inspector.py' only evaluates the assembly and identifies assembly errors. The 'valid_contig.fa' includes original uncorrected contigs. Error correction is done by running additional step of "inspector-correct.py -i inspector_out/ --datatype pacbio-hifi ". You will find corrected assembly in a file named 'corrected_contig.fa'. 

Best,
Maggi

**Comment by hq66** [comment]
> Hello,
> 
> The script 'inspector.py' only evaluates the assembly and identifies assembly errors. The 'valid_contig.fa' includes original uncorrected contigs. Error correction is done by running additional step of "inspector-correct.py -i inspector_out/ --datatype pacbio-hifi ". You will find corrected assembly in a file named 'corrected_contig.fa'.
> 
> Best, Maggi

Thanks for your reply!
