### ISSUE TITLE
there no mixed in -r parameter

### ISSUE THREAD

**Issue by zhoudreames** [Maggi-Chen/Inspector#2]
in your inspector.py,there are not mixed type,why?
parser.add_argument('-d','--datatype',type=str,default='clr',help='Input read type. (clr, hifi, nanopore) [clr]')

**Comment by zhoudreames** [comment]
@Maggi-Chen  i am so sorry to disturb  you,could you help me ?

**Comment by Maggi-Chen** [comment]
By 'mixed type', if you mean short read plus long read, Inspector does not support that yet. We are planning to include short reads as additional input for smaller assembly error identification, but not in near future though. Read alignment is quite time-consuming, and long read alone can identify most of the assembly errors based on our benchmark, especially using HiFi reads. 

If you have mixed types of long reads (i.e., CLR and HiFi), it should be fine if you set the data type to 'clr' for the assembly evaluation. There might be potential issues if you want to perform error correction following the evaluation step, as we use Flye for local assembly, which does not support mixed data type. 

Bests,
Maggi

**Comment by zhoudreames** [comment]
thanks~
