### ISSUE TITLE
Typo in inspector-correct.py

### ISSUE THREAD

**Issue by SaelinB** [Maggi-Chen/Inspector#20]
Hello, using inspector-correct.py with --datatype nano-corr leads to an error that data type is invalid, due to a space in front of nano-corr in this line:

`if inscor_args.datatype not in ['pacbio-raw','pacbio-hifi', 'pacbio-corr', 'nano-raw',' nano-corr']:`

**Comment by yuweisong-uab** [comment]
Hi,
Thanks for pointing it out. We have fixed this typo.

Best,
Yuwei

**Comment by yuweisong-uab** [comment]
Hi,
Thanks for pointing out. We have fixed this typo.

Best,
Yuwei
