### ISSUE TITLE
cat: test_out/ae_merge_workspace/inv_merged_*: No such file or directory

### ISSUE THREAD

**Issue by yue131** [Maggi-Chen/Inspector#22]
I'd like to inspector to perform assembly correction of two haplotype-resolved HiFi assemblies of a human individual; So i fristly run the test dataset to validate successful installation of inspector.  In the log file, i found a warning :
cat: test_out/ae_merge_workspace/inv_merged_*: No such file or directory; 
However in the directory of test_out/ae_merge_workspace/, there was a file named inv_merged_ctg1.  so do I need to worry about this warning? and only 2 structure error and 298 small-scale assembly error were present in the summary_statistics file. Is the difference of result caused by different versions of dependencies for Inspector?

Any help would be greatly appreciated,
Jingwei Yue!

####the log file:####
  import pandas.util.testing as tm
[M::mm_idx_gen::0.048*1.05] collected minimizers
[M::mm_idx_gen::0.079*3.31] sorted minimizers
[M::main::0.079*3.31] loaded/built the index for 2 target sequence(s)
[M::mm_mapopt_update::0.091*3.00] mid_occ = 70
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2
[M::mm_idx_stat::0.100*2.83] distinct minimizers: 242594 (96.40% are singletons); average occurrences: 1.138; average spacing: 5.328; total length: 1470648
[M::worker_pipeline::14.646*7.00] mapped 6532 sequences
[M::main] Version: 2.26-r1175
[M::main] CMD: minimap2 -a -Q -N 1 -I 10G -t 8 test_out/valid_contig.fa testdata/read_test.fastq.gz
[M::main] Real time: 14.660 sec; CPU: 102.577 sec; Peak RSS: 1.226 GB
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
Collect info from ctg2
cat: test_out/ae_merge_workspace/inv_merged_*: No such file or directory
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
end n100

####files in the directory of test_out/ae_merge_workspace/
deletion-merged
del_merged_ctg1
insertion-merged
ins_merged_ctg1
inversion-merged

#######Dependencies for Inspector:
python 3.7
minimap2 2.2
samtools 1.6

**Comment by Johnsonzcode** [comment]
Same warning

**Comment by yuweisong-uab** [comment]
Hi,
Here you don't need to worry about this warning as long Inspect complete the running and showed "Inspector evaluation finished. Bye." in the log file.

Best,
Yuwei
