### ISSUE TITLE
bgzip format for contig fasta

### ISSUE THREAD

**Issue by zhengxinchang** [Maggi-Chen/Inspector#25]
Hi, all

Does inspectory support bgzip format for contig fasta? When I running inspector on bgziped fasta files, it failed with no error messages were returned.

Best regards,
Xinchang

**Comment by yuweisong-uab** [comment]
Hi, 
Thanks for the comments!
The current inspector supports only references in FASTA format, not the compressed format. We will consider including additional formats in future versions.

Best regards,
Yuwei
