### ISSUE TITLE
Bug in debreak_detect.py in the release tar ball

### ISSUE THREAD

**Issue by hp2048** [Maggi-Chen/Inspector#26]
Hi
I notice that the release tar.gz has an error in the `debreak_detect.py` at line 428. Following statement is missing parenthesis.

```
print 'Collect info from '+chrom
```

Cheers

**Comment by yuweisong-uab** [comment]
Hi,
Thank you for the comment. 
We have revised the released source code. Please check and let us know if you have any questions.

Best,
Yuwei
