### ISSUE TITLE
Update minimap2 to 2.28

### ISSUE THREAD

**Issue by baozg** [Maggi-Chen/Inspector#29]
Hi, @Maggi-Chen 

`minimap2` improve a lot about high-repetitive regions both on assembly and reads mode. Have you consider to update the minimap2 2.15 to 2.28 (https://github.com/lh3/minimap2/releases)? I am not sure how much need change for statistics modeling part of inspector?

**Comment by yuweisong-uab** [comment]
Hi,

Thank you so much for the suggestion!
We will test out and try to include the newest minimap2 in our next release!

Best,
Yuwei

**Comment by fergsc** [comment]
Hi,

Has there been any progress on this? I am very interested in using Inspector to improve my genomes, however Minimap2-2.15 is very old and was released in Janurary 2019. Using a 5 year old version of minimap2 is problomatic.

Thanks.

**Comment by AndreaGuarracino** [comment]
@fergsc, I see that they are using minimap2 >= 2.28 https://github.com/bioconda/bioconda-recipes/blob/master/recipes/inspector/meta.yaml#L20, so all good!
