### ISSUE TITLE
Can you please migrate to python3?

### ISSUE THREAD

**Issue by 0seastar0** [Maggi-Chen/Inspector#4]
python2 is no longer supported. Could you please migrate to python3? Thank you.

**Comment by 0seastar0** [comment]
"DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support"

**Comment by Maggi-Chen** [comment]
Thank you for the information. We are planning to make Inspector support both python2 and python3. It will probably be done early 2022.

Bests,
Maggi

**Comment by 0seastar0** [comment]
Thank you, Maggi! Looking forward to the update. Cheers, Sara
