### ISSUE TITLE
Run Inspector with Illumina data

### ISSUE THREAD

**Issue by mpalmada** [Maggi-Chen/Inspector#7]
Hi!

I want to compare the results of one run of Inspector and one run of merqury using Illumina data, which datatype should I add if I use Illumina data?

Thanks a lot!
Marc

**Comment by Maggi-Chen** [comment]
Hello Marc,

Sorry for the late response. Unfortunately, Inspector is designed for long-read sequencing, and it does not support Illumina data as input. 

Thanks,
Maggi
